name = "nozzle-configurator"
compatibility_date = "2024-06-25"

[env.production]
name = "nozzle-configurator"

[build]
command = "yarn build"
cwd = "."

[build.upload]
format = "directory"
dir = "./dist"

[[env.production.routes]]
pattern = "*"
custom_domain = true