name = "nozzle-configurator"
compatibility_date = "2024-06-25"
pages_build_output_dir = "dist"

# Build configuration
build = { command = "yarn build" }

# Environment variables
[env.production.vars]
NODE_ENV = "production"
CLOUDFLARE_PAGES = "true"

# Functions configuration for WASM support
[functions]
compatibility_date = "2024-06-25"
compatibility_flags = ["nodejs_compat"]