name = "nozzle-configurator"
compatibility_date = "2024-06-25"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "nozzle-configurator"

[build]
command = "yarn build"
cwd = "."

[build.upload]
format = "directory"
dir = "./dist"

[[env.production.routes]]
pattern = "*"
custom_domain = true

# WASM support
[vars]
NODE_ENV = "production"
CLOUDFLARE_PAGES = "true"

# WebAssembly compatibility
[wasm]
bindings = []

# Functions configuration
[functions]
compatibility_date = "2024-06-25"
compatibility_flags = ["nodejs_compat"]